-- AlterTable
ALTER TABLE `PointTransaction` ADD COLUMN `branchId` VARCHAR(191) NULL,
    ADD COLUMN `campaignId` VARCHAR(191) NULL,
    ADD COLUMN `couponId` VARCHAR(191) NULL,
    ADD COLUMN `eventId` VARCHAR(191) NULL,
    ADD COLUMN `receiptId` VARCHAR(191) NULL,
    ADD COLUMN `referenceType` ENUM('RECEIPT', 'CAMPAIGN', 'COUPON', 'EVENT', 'MISSION', 'REFERRAL', 'ADJUST') NULL,
    ADD COLUMN `shopId` VARCHAR(191) NULL;
