-- AlterTable
ALTER TABLE `BannerHome` ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `BannerLogin` ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `BannerOtp` ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `BannerPoint` ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `BannerRegister` ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `BannerTerms` ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `BannerUpload` ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `BannerWelcome` ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `Campaign` ADD COLUMN `linkShare` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `Event` ADD COLUMN `linkShare` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `Popup` ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `Reward` ADD COLUMN `linkShare` VARCHAR(191) NULL;
