-- AlterTable
ALTER TABLE `User` MODIFY `role` ENUM('USER', 'ADMIN', 'ADMINMARKETING', 'CRMMANAGEMENT', 'STAFF') NOT NULL DEFAULT 'USER';

-- AlterTable
ALTER TABLE `User_Lost` MODIFY `role` ENUM('USER', 'ADMIN', 'ADMINMARKETING', 'CRMMANAGEMENT', 'STAFF') NOT NULL DEFAULT 'USER';
